config/routes.rb
Rails.application.routes.draw do
  get 'pdfs/trafficking'

  resources :test_mes

  get 'report_gender/index'

  get 'report_gender/generate'

  get 'report_gender/trafficking'

  get 'report_gender/theology'

  resources :docs
  resources :facilities

  get 'form_gender/index'

  get 'form_gender/trafficking'

  get 'gender/index'

  get 'gender/trafficking'

  get 'report_health/index'

  get 'form_health/index'

  get 'forms/new'

  #root to: 'visitors#index'
  #get 'visitors/programs'
  #post 'visitors/programs'
  devise_for :users
  devise_scope :user do
    authenticated :user do
      #root to: 'visitors#index', as: :authenticated_root
      root to: 'home#index', as: :authenticated_root
      get 'visitors/programs'
      get 'forms/new'
      post 'forms/new'
      get 'forms/create'
      post 'forms/create'
      get 'form_health/index'
      post 'form_health/index'
      get 'form_health/mnh'
      post 'form_health/mnh'
      get 'form_health/training'
      post 'form_health/training'
      get 'form_health/iptt'
      post 'form_health/iptt'
      get 'form_health/reproductive_health_output_two'
      post 'form_health/reproductive_health_output_two'
      get 'form_health/reproductive_health_output_three'
      post 'form_health/reproductive_health_output_three'
      get 'form_health/reproductive_health_output_four'
      post 'form_health/reproductive_health_output_four'
      get 'form_health/hiv'
      post 'form_health/hiv'
      get 'form_health/giz'
      post 'form_health/giz'
      get 'form_health/create'
      post 'form_health/create'
      get 'form_gender/index'
      post 'form_gender/index'
      get 'form_gender/trafficking'
      post 'form_gender/trafficking'
      get 'form_gender/theology'
      post 'form_gender/theology'
      get 'form_gender/create'
      post 'form_gender/create'
      get 'report_health/generate'
      post 'report_health/generate'
      get 'report_health/mnh'
      post 'report_health/mnh'
      get 'report_health/training'
      post 'report_health/training'
      get 'report_health/iptt'
      post 'report_health/iptt'
      get 'report_health/hiv'
      post 'report_health/hiv'
      get 'report_health/giz'
      post 'report_health/giz'
      get 'report_gender/generate'
      post 'report_gender/generate'
      get 'report_gender/trafficking'
      post 'report_gender/trafficking'
      get 'report_gender/theology'
      post 'report_gender/theology'
      get 'home/index'
      post 'home/index'
      get 'facilities/index'
      post 'facilities/index'
      get 'facilities/new'
      post 'facilities/new'
      get 'docs/index'
      post 'docs/index'
      get 'docs/new'
      post 'docs/new'
      get 'report_health/reproductive_health_output_two'
      post 'report_health/reproductive_health_output_two'
      get 'report_health/reproductive_health_output_three'
      post 'report_health/reproductive_health_output_three'
      get 'report_health/reproductive_health_output_four'
      post 'report_health/reproductive_health_output_four'
      get 'home/index'
      post 'home/index'
      get 'pdfs/trafficking'
      post 'pdfs/trafficking'
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
 end
  resources :users
end

app/models/college.rb
class College < ActiveRecord::Base
end

app/models/doc.rb
class Doc < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :name, presence: true # Make sure the owner's name is present.
end

app/models/facility.rb
class Facility < ActiveRecord::Base
end

app/models/form.rb
class Form < ActiveRecord::Base
end

app/models/form_health_giz.rb
class FormHealthGiz < ActiveRecord::Base
end

app/models/form_health_hiv.rb
class FormHealthHiv < ActiveRecord::Base
end

app/models/form_health_iptt.rb
class FormHealthIptt < ActiveRecord::Base
end

app/models/form_health_mnh.rb
class FormHealthMnh < ActiveRecord::Base
end

app/models/form_training.rb
class FormTraining < ActiveRecord::Base
end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/models/test_me.rb
class TestMe < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/form_gender_controller.rb
class FormGenderController < ApplicationController
  def index
  end
  def create
     if params.has_key?("form_gender_trafficking")
      @form = FormGenderTrafficking.new(params[:form_gender_trafficking].permit(:start_date, :end_date, :trfk_cases_reported, :trfk_cases_resolved, :trfk_percent_reduction, :trfk_incorporation_in_church, :trfk_outreach, :trfk_mobile_clinic, :trfk_awareness, :trfk_informal_justice, :trfk_other_service_providers, :trfk_rescued, :trfk_court_rehabilitated, :trfk_network_initiatives, :trfk_interagency_meet, :trfk_issues_raised))
 @form.save
     elsif params.has_key?("form_gender_theology")
        @form = FormGenderTheology.new(params[:form_gender_theology].permit(:start_date, :end_date, :theo_training_manuals,  :theo_f_and_m_teachers,  :theo_context_text,  :theo_counselors,   :theo_code_conduct,  :theo_code_conduct_emp,  :theo_diaconal_strategies,   :theo_develop_advocacy_strategy,   :theo_using_advocacy_strategy,  :theo_monit_visit,  :theo_reports_produced, :theo_church_leader_tot, :theo_church_joint_declaration))
        @form.save
     end

     redirect_to '/form_gender/index'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/helpers/form_gender_helper.rb
module FormGenderHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/gender_helper.rb
module GenderHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pdfs_helper.rb
module PdfsHelper
end

app/helpers/test_mes_helper.rb
module TestMesHelper
end

app/views/form_gender/index.html.erb
  	
    <div class="page-content">
    	<div class="row">
		  <div class="col-md-2">
		 
  <div class="sidebar content-box" style="display: block;">
                  <ul class="nav">
                      <!-- Main menu -->
                      
                      <li><%= link_to 'Home', home_index_path %></li>

                      <li class="dropdown">
                           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                              Data Entry <b class="caret"></b>
                           </a>
                           <!-- Sub menu -->
                           <ul>
                             <li><a href="#">Resource and Finance</a></li>
                             <li><%= link_to 'Gender Justice', form_gender_index_path %></li>
                             <li><%= link_to 'Health', form_health_index_path %></li>
                   <li><a href="#">Monitoring and Evaluation</a></li>
                          </ul>
                      </li>

                      <li class="dropdown">
                           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                              Reports <b class="caret"></b>
                           </a>
                           <!-- Sub menu -->
                           <ul>
                             <li><a href="#">Resource and Finance</a></li>
                             <li><%= link_to 'Gender Justice', report_gender_index_path %></li>
                             <li><%= link_to 'Health', report_health_index_path %></li>
                   <li><a href="#">Monitoring and Evaluation</a></li>
                          </ul>
                      </li>

                      <li class="dropdown">
                           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                              Documents <b class="caret"></b>
                           </a>
                           <!-- Sub menu -->
                           <ul>
                            <li> <%= link_to 'View', docs_path %></li>
                             <li><%= link_to 'Upload', docs_new_path %></li>
                          </ul>
                      </li>

<!--
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                              Partners <b class="caret"></b>
                          </a>
                           <ul>
                            <li> <%= link_to 'Facilities', facilities_path %></li>
                             <li><%= link_to 'Institutions', forms_new_path %></li>
                          </ul>
                      </li>
            --> 
                  </ul>
               </div>


     
		  </div>
		  <div class="col-md-10">
		  	<div class="row">

		  	</div>

		  	<div class="row">
		  		<div class="col-md-12 panel-warning">
		  			<div class="content-box-header panel-heading">
	  					<div class="panel-title ">Gender Justice - Form selection</div>
						
						<div class="panel-options">
							<a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
							<a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
						</div>
		  			</div>
		  			<div class="content-box-large box-with-header">
This is a Web Based Database Management System for the Norwegian Church Aid. It contains quarterly data and generates reports as required by the NCA's programs. Below are the areas for which this database system stores, analyses and generates reports.



						<br /><br />
						<br /><br />
<ul>
<li><%=link_to 'Human Trafficking', form_gender_trafficking_path%></li>
<li><%=link_to 'Theology', form_gender_theology_path%></li>
</ul>
						<br /><br />
					</div>
		  		</div>
		  	</div>

		  	<div class="content-box-large">
		  	</div>
		  </div>
		</div>
    </div>

    <footer>
         <div class="container">
         
            <div class="copy text-center">
               Copyright 2015 <a href='#'>Compu Networks</a>
            </div>
            
         </div>
      </footer>

app/views/form_gender/theology.html.erb
<script type='text/javascript'>

(function()
{
  if( window.localStorage )
  {
    if( !localStorage.getItem( 'firstLoad' ) )
    {
      localStorage[ 'firstLoad' ] = true;
      window.location.reload();
    }  
    else
      localStorage.removeItem( 'firstLoad' );
  }
})();

</script>

<script>
	function assignStartDate() {
				document.getElementById("form_gender_theology_start_date").value = $("#start_date_picker").val();
			}
			function assignEndDate() {
				document.getElementById("form_gender_theology_end_date").value = $("#end_date_picker").val();
			}
</script>	
    <div class="page-content">
    	<div class="row">
		  <div class="col-md-2">
		  	<div class="sidebar content-box" style="display: block;">
                <ul class="nav">
                    <!-- Main menu -->
                    <li class="current"><a href="home/index"><i class="glyphicon glyphicon-home"></i>Home</a></li>

                    <li class="dropdown">
                         <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                           <i class="glyphicon glyphicon-tasks"></i> Data Entry <b class="caret"></b>
                         </a>
                         <!-- Sub menu -->
                         <ul>
                          <li> <%= link_to 'Resource and Finance', forms_new_path %></li>
                           <li><%= link_to 'Gender Justice', form_gender_index_path %></li>
                           <li><%= link_to 'Health', form_health_index_path %></li>
  			   <li><%= link_to 'Monitoring and Evaluation', forms_new_path %></li>
                        </ul>
                    </li>

                    <li class="dropdown">
                         <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                           <i class="glyphicon glyphicon-stats"></i> Reports <b class="caret"></b>
                         </a>
                         <!-- Sub menu -->
                         <ul>
                          <li> <%= link_to 'Resource and Finance', forms_new_path %></li>
                           <li><%= link_to 'Gender Justice', forms_new_path %></li>
                           <li><%= link_to 'Health', report_health_index_path %></li>
  			   <li><%= link_to 'Monitoring and Evaluation', forms_new_path %></li>
                        </ul>
                    </li>

                    <li class="dropdown">
                         <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                           <i class="glyphicon glyphicon-download-alt"></i> Documents <b class="caret"></b>
                         </a>
                         <!-- Sub menu -->
                         <ul>
                          <li> <%= link_to 'View', forms_new_path %></li>
                           <li><%= link_to 'Upload', forms_new_path %></li>
                        </ul>
                    </li>


                    <li><a href="tables.html"><i class="glyphicon glyphicon-list"></i>Partners</a></li>
                </ul>
             </div>
		  </div>
		  <div class="col-md-10">
		  	<div class="row">

		  	</div>

		  	<div class="row">
		  		<div class="col-md-12 panel-warning">
		  			<div class="content-box-header panel-heading">
	  					<div class="panel-title ">Data Entry - Theology</div>
						
						<div class="panel-options">
							<a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
							<a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
						</div>
		  			</div>
		  			<div class="content-box-large box-with-header">
			  			



<!--form-->
	
	  					<div class="content-box-large">
			  				
			  				<div class="panel-body">





<%= form_for :form_gender_theology, :url => { :action => :create }	 do |f| %>
	

			  					<!--form action="/forms/create" method="post"-->
									<fieldset>







		  				<div class="panel-body">





<%= f.hidden_field :start_date, :value => ""%>
<%= f.hidden_field :end_date, :value => "" %>





		  					<table class="table table-bordered">
				              <thead>
				                <tr>
				                  <th>Indicator</th>
				                  <th>Value</th>
				                </tr>
				              </thead>
				              <tbody>
						<tr>
															<td>Start Date</td>
															<td><div class="bfh-datepicker" data-format="y-m-d" data-date="today" id="start_date_picker" onchange="assignStartDate()"></div></td>
														</tr>
														<tr>
															<td>End Date</td>
															<td><div class="bfh-datepicker" data-format="y-m-d" data-date="today" id="end_date_picker" onchange="assignEndDate()"></div></td>
														</tr>	
				                <tr>
				                  <td colspan = "2"><b></b></td>
				                </tr>
				                <tr>
				                  <td>Number of training manuals produced</td>
				                  <td><%= f.text_field :theo_training_manuals, autofocus: true, class: "form-control" %></td>
				                </tr>
				                <tr>
				                  <td>Number of female and male teachers, health workers trained in material on human rights and theology</td>
				                  <td><%= f.text_field :theo_f_and_m_teachers, autofocus: true, class: "form-control" %></td>
				                </tr>
				                
				                <tr>
				                  <td>Number of contextual text interpretations of biblical texts related to Human rights and justice are produced by churches and distributed to 40 % of the parishes</td>
				                  <td><%= f.text_field :theo_context_text, autofocus: true, class: "form-control" %></td>
				                </tr>
				                <tr>
				                  <td>Number of counselors trained </td>
				                  <td><%= f.text_field :theo_counselors, autofocus: true, class: "form-control" %></td>
				                </tr>
				                <tr>
				                  <td>Number of churches that have introduced and endorsed code of conduct </td>
				                  <td><%= f.text_field :theo_code_conduct, autofocus: true, class: "form-control" %></td>
				                </tr>
				                <tr>
				                  <td>Number of churches have decided and introduced code of conduct and employees have signed them.</td>
				                  <td><%= f.text_field :theo_code_conduct_emp, autofocus: true, class: "form-control" %></td>
				                </tr>              


                       
				                <tr>
				                  <td>Number of churches that have developed diaconal strategies on the foundation of theology and human rights and compassion, fighting injustice, violence and oppression with a special focus upon taking care of survivors of trafficking and GBV.</td>
				                  <td><%= f.text_field :theo_diaconal_strategies, autofocus: true, class: "form-control" %></td>
				                </tr>
				                
				                <tr>
				                  <td>Number of churches that have developmed of advocacy strategy</td>
				                  <td><%= f.text_field :theo_develop_advocacy_strategy, autofocus: true, class: "form-control" %></td>
				                </tr>
				                <tr>
				                  <td>Number of churches  using the advocacy strategy. </td>
				                  <td><%= f.text_field :theo_using_advocacy_strategy, autofocus: true, class: "form-control" %></td>
				                </tr>
				                <tr>
				                  <td>NUmber of monitoring visits conducted</td>
				                  <td><%= f.text_field :theo_monit_visit, autofocus: true, class: "form-control" %></td>
				                </tr>
				                 <tr>
				                  <td>Number of reports produced.</td>
				                  <td><%= f.text_field :theo_reports_produced, autofocus: true, class: "form-control" %></td>
				                </tr>
				                <tr>
				                  <td>Number of church leaders trained as TOTs</td>
				                  <td><%= f.text_field :theo_church_leader_tot, autofocus: true, class: "form-control" %></td>
				                </tr>
				                 <tr>
				                  <td>Joint declaration by church leaders on Gender based violence</td>				                 
				                  <td><%= f.select :theo_church_joint_declaration, options_for_select( ["Yes","No"]),autofocus: true, class: "form-control" %></td>
				                </tr>
				                

				              </tbody>
				            </table>
		  				</div>




								
									</fieldset>
									<div>
 
											<%= submit_tag "Finish", class:"btn btn-primary" %>
									</div>
								<!--/form-->
  <% end %>

			  				</div>
			  			</div>
	  				




						<br /><br />
					</div>
		  		</div>
		  	</div>

		  </div>
		</div>
    </div>

    <footer>
         <div class="container">
         
            <div class="copy text-center">
               Copyright 2015 <a href='#'>Compu Networks</a>
            </div>
            
         </div>
      </footer>

app/views/form_gender/trafficking.html.erb
<script type='text/javascript'>

(function()
{
  if( window.localStorage )
  {
    if( !localStorage.getItem( 'firstLoad' ) )
    {
      localStorage[ 'firstLoad' ] = true;
      window.location.reload();
    }  
    else
      localStorage.removeItem( 'firstLoad' );
  }
})();

</script>

<script>
	function assignStartDate() {
				document.getElementById("form_gender_trafficking_start_date").value = $("#start_date_picker").val();
			}
			function assignEndDate() {
				document.getElementById("form_hgender_trafficking_end_date").value = $("#end_date_picker").val();
			}
</script>	
    <div class="page-content">
    	<div class="row">
		  <div class="col-md-2">
		  	<div class="sidebar content-box" style="display: block;">
                <ul class="nav">
                    <!-- Main menu -->
                    <li class="current"><a href="home/index"><i class="glyphicon glyphicon-home"></i>Home</a></li>

                    <li class="dropdown">
                         <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                           <i class="glyphicon glyphicon-tasks"></i> Data Entry <b class="caret"></b>
                         </a>
                         <!-- Sub menu -->
                         <ul>
                          <li> <%= link_to 'Resource and Finance', forms_new_path %></li>
                           <li><%= link_to 'Gender Justice', form_gender_index_path %></li>
                           <li><%= link_to 'Health', form_health_index_path %></li>
  			   <li><%= link_to 'Monitoring and Evaluation', forms_new_path %></li>
                        </ul>
                    </li>

                    <li class="dropdown">
                         <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                           <i class="glyphicon glyphicon-stats"></i> Reports <b class="caret"></b>
                         </a>
                         <!-- Sub menu -->
                         <ul>
                          <li> <%= link_to 'Resource and Finance', forms_new_path %></li>
                           <li><%= link_to 'Gender Justice', forms_new_path %></li>
                           <li><%= link_to 'Health', report_health_index_path %></li>
  			   <li><%= link_to 'Monitoring and Evaluation', forms_new_path %></li>
                        </ul>
                    </li>

                    <li class="dropdown">
                         <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                           <i class="glyphicon glyphicon-download-alt"></i> Documents <b class="caret"></b>
                         </a>
                         <!-- Sub menu -->
                         <ul>
                          <li> <%= link_to 'View', forms_new_path %></li>
                           <li><%= link_to 'Upload', forms_new_path %></li>
                        </ul>
                    </li>


                    <li><a href="tables.html"><i class="glyphicon glyphicon-list"></i>Partners</a></li>
                </ul>
             </div>
		  </div>
		  <div class="col-md-10">
		  	<div class="row">

		  	</div>

		  	<div class="row">
		  		<div class="col-md-12 panel-warning">
		  			<div class="content-box-header panel-heading">
	  					<div class="panel-title ">Data Entry - Human Trafficking</div>
						
						<div class="panel-options">
							<a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
							<a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
						</div>
		  			</div>
		  			<div class="content-box-large box-with-header">
			  			



<!--form-->
	
	  					<div class="content-box-large">
			  				
			  				<div class="panel-body">





<%= form_for :form_gender_trafficking, :url => { :action => :create }	 do |f| %>
	

			  					<!--form action="/forms/create" method="post"-->
									<fieldset>







		  				<div class="panel-body">





<%= f.hidden_field :start_date, :value => ""%>
<%= f.hidden_field :end_date, :value => "" %>





		  					<table class="table table-bordered">
				              <thead>
				                <tr>
				                  <th>Indicator</th>
				                  <th>Value</th>
				                </tr>
				              </thead>
				              <tbody>
						<tr>
															<td>Start Date</td>
															<td><div class="bfh-datepicker" data-format="y-m-d" data-date="today" id="start_date_picker" onchange="assignStartDate()"></div></td>
														</tr>
														<tr>
															<td>End Date</td>
															<td><div class="bfh-datepicker" data-format="y-m-d" data-date="today" id="end_date_picker" onchange="assignEndDate()"></div></td>
														</tr>	
				                <tr>
				                  <td colspan = "2"><b></b></td>
				                </tr>
				                <tr>
				                  <td>Forms of trafficking cases reported and documented</td>
				                  <td><%= f.text_field :trfk_cases_reported, autofocus: true, class: "form-control" %></td>
				                </tr>
				                <tr>
				                  <td>Number of trafficking cases resolved by law enforcement agencies</td>
				                  <td><%= f.text_field :trfk_cases_resolved, autofocus: true, class: "form-control" %></td>
				                </tr>
				                <tr>
				                  <td>% reduction of GBV cases in the churches and communities</td>
				                  <td><%= f.text_field :trfk_percent_reduction, autofocus: true, class: "form-control" %></td>
				                </tr>
				                <tr>
				                  <td>Number of churches incorporating human rights issues in their church services</td>
				                  <td><%= f.text_field :trfk_incorporation_in_church, autofocus: true, class: "form-control" %></td>
				                </tr>

				                <tr>
				                  <td>Number of outreach meetings</td>
				                  <td><%= f.text_field :trfk_outreach, autofocus: true, class: "form-control" %></td>
				                </tr>
				                <tr>
				                  <td>Number of legal mobile clinics</td>
				                  <td><%= f.text_field :trfk_mobile_clinic, autofocus: true, class: "form-control" %></td>
				                </tr>
				                <tr>
				                  <td>Number of awareness campaigns</td>
				                  <td><%= f.text_field :trfk_awareness, autofocus: true, class: "form-control" %></td>
				                </tr>
				                <tr>
				                  <td>Number of cases reported and resolved through informal justice systems</td>
				                  <td><%= f.text_field :trfk_informal_justice, autofocus: true, class: "form-control" %></td>
				                </tr>
				                


                                <tr>
				                  <td>Number of human trafficking victims identified and supported by other service providers</td>
				                  <td><%= f.text_field :trfk_other_service_providers, autofocus: true, class: "form-control" %></td>
				                </tr>
				                <tr>
				                  <td>Number of cases reported and resolved through informal justice systemsNumber of victims rescued, rehabiliated and reintegrated.</td>
				                  <td><%= f.text_field :trfk_rescued, autofocus: true, class: "form-control" %></td>
				                </tr>
				                <tr>
				                  <td>Number of courts/safe houses rehabilitated</td>
				                  <td><%= f.text_field :trfk_court_rehabilitated, autofocus: true, class: "form-control" %></td>
				                </tr>
				                <tr>
				                  <td>Number of networking iniatiaves</td>
				                  <td><%= f.text_field :trfk_network_initiatives, autofocus: true, class: "form-control" %></td>
				                </tr>




				                <tr>
				                  <td>Number of sustained meetings held by interagency operatives</td>
				                  <td><%= f.text_field :trfk_interagency_meet, autofocus: true, class: "form-control" %></td>
				                </tr>
				                <tr>
				                  <td>Trafficking issues raised and responded to</td>
				                  <td><%= f.text_field :trfk_issues_raised, autofocus: true, class: "form-control" %></td>
				                </tr>
				                

				              </tbody>
				            </table>
		  				</div>




								
									</fieldset>
									<div>
 
											<%= submit_tag "Finish", class:"btn btn-primary" %>
									</div>
								<!--/form-->
  <% end %>

			  				</div>
			  			</div>
	  				




						<br /><br />
					</div>
		  		</div>
		  	</div>

		  </div>
		</div>
    </div>

    <footer>
         <div class="container">
         
            <div class="copy text-center">
               Copyright 2015 <a href='#'>Compu Networks</a>
            </div>
            
         </div>
      </footer>