config/routes.rb
Rails.application.routes.draw do
  get 'pdfs/trafficking'

  resources :test_mes

  get 'report_gender/index'

  get 'report_gender/generate'

  get 'report_gender/trafficking'

  get 'report_gender/theology'

  resources :docs
  resources :facilities

  get 'form_gender/index'

  get 'form_gender/trafficking'

  get 'gender/index'

  get 'gender/trafficking'

  get 'report_health/index'

  get 'form_health/index'

  get 'forms/new'

  #root to: 'visitors#index'
  #get 'visitors/programs'
  #post 'visitors/programs'
  devise_for :users
  devise_scope :user do
    authenticated :user do
      #root to: 'visitors#index', as: :authenticated_root
      root to: 'home#index', as: :authenticated_root
      get 'visitors/programs'
      get 'forms/new'
      post 'forms/new'
      get 'forms/create'
      post 'forms/create'
      get 'form_health/index'
      post 'form_health/index'
      get 'form_health/mnh'
      post 'form_health/mnh'
      get 'form_health/training'
      post 'form_health/training'
      get 'form_health/iptt'
      post 'form_health/iptt'
      get 'form_health/reproductive_health_output_two'
      post 'form_health/reproductive_health_output_two'
      get 'form_health/reproductive_health_output_three'
      post 'form_health/reproductive_health_output_three'
      get 'form_health/reproductive_health_output_four'
      post 'form_health/reproductive_health_output_four'
      get 'form_health/hiv'
      post 'form_health/hiv'
      get 'form_health/giz'
      post 'form_health/giz'
      get 'form_health/create'
      post 'form_health/create'
      get 'form_gender/index'
      post 'form_gender/index'
      get 'form_gender/trafficking'
      post 'form_gender/trafficking'
      get 'form_gender/theology'
      post 'form_gender/theology'
      get 'form_gender/create'
      post 'form_gender/create'
      get 'report_health/generate'
      post 'report_health/generate'
      get 'report_health/mnh'
      post 'report_health/mnh'
      get 'report_health/training'
      post 'report_health/training'
      get 'report_health/iptt'
      post 'report_health/iptt'
      get 'report_health/hiv'
      post 'report_health/hiv'
      get 'report_health/giz'
      post 'report_health/giz'
      get 'report_gender/generate'
      post 'report_gender/generate'
      get 'report_gender/trafficking'
      post 'report_gender/trafficking'
      get 'report_gender/theology'
      post 'report_gender/theology'
      get 'home/index'
      post 'home/index'
      get 'facilities/index'
      post 'facilities/index'
      get 'facilities/new'
      post 'facilities/new'
      get 'docs/index'
      post 'docs/index'
      get 'docs/new'
      post 'docs/new'
      get 'report_health/reproductive_health_output_two'
      post 'report_health/reproductive_health_output_two'
      get 'report_health/reproductive_health_output_three'
      post 'report_health/reproductive_health_output_three'
      get 'report_health/reproductive_health_output_four'
      post 'report_health/reproductive_health_output_four'
      get 'home/index'
      post 'home/index'
      get 'pdfs/trafficking'
      post 'pdfs/trafficking'
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
 end
  resources :users
end

app/controllers/form_health_controller.rb
class FormHealthController < ApplicationController
  def index
  end
  def create
    
     if params.has_key?("form_health_mnh")
      @form = FormHealthMnh.new(params[:form_health_mnh].permit(:start_date, :end_date, :facility, :service_del_svd, :service_del_ve, :service_del_mart_death, :service_del_ref, :service_del_ref_eclampsia, :service_del_ref_labour, :service_del_ref_aph, :service_del_ref_cs, :service_del_ref_breech, :service_del_ref_twins, :neonates_male, :neonates_female, :nnd_male, :nnd_female, :nnd_ref, :nnd_fsb, :nnd_msb, :nnd_premature, :nnd_lbw, :outreach_preg_mother, :outreach_initial, :outreach_2nd, :outreach_3rd, :outreach_4th, :outreach_male, :outreach_underfive_initial, :outreach_underfive_subsequent, :outreach_female, :mobilization_men, :slas, :facility_planning, :inf_prev_male, :inf_prev_female, :exl_bf_male, :exl_bf_female, :hac_train_male, :hac_train_female, :menu_male, :menu_female, :nutri_male, :nutri_female, :tpt_comm_male, :tpt_comm_female, :sf_mothood_male, :sf_mothood_female, :hac_male, :hac_female, :cluster_male, :cluster_female, :dec_male, :dec_female, :skilled_doc, :skilled_cli, :skilled_nur, :support_hsa, :support_PA, :support_HCW, :support_guard, :support_drv, :maintenance_veh, :maintenance_mcycle, :maintenance_comp, :maintenance_boat, :maintenance_rad, :water_run, :water_borehole, :water_elec, :water_solar, :water_torch, :demo_garden, :hearth, :preg_shelter, :sup_DHO, :sup_coord, :sup_focal, :sup_NCA, :sup_zone))
 @form.save
    elsif params.has_key?("form_health_training")
    @form = FormHealthTraining.new(params[:form_health_training].permit(:start_date, :end_date, :trn_hundred_percent_license, :trn_satisfaction_level, :trn_BSC_RM_Curr, :trn_tutor_perf_tools, :trn_mentor_skills, :trn_reduction_unprof_student, :trn_tutor_induct_midwife, :trn_strategic_plans, :trn_ops_plans, :trn_good_governance, :trn_motivated_pupils, :trn_research, :trn_ntwk_meetings, :trn_MOU, :trn_monitoring, :trn_college, :trn_research_tut, :trn_management_systems_typ1, :trn_management_systems_num1, :trn_management_systems_typ2, :trn_management_systems_num2, :trn_management_systems_typ3, :trn_management_systems_num3, :trn_teaching_materials_typ1, :trn_teaching_materials_num1, :trn_teaching_materials_typ2, :trn_teaching_materials_num2, :trn_teaching_materials_typ3, :trn_teaching_materials_num3, :trn_capacity_built_typ1, :trn_capacity_built_num1, :trn_capacity_built_typ2, :trn_capacity_built_num2, :trn_capacity_built_typ3, :trn_capacity_built_num3, :trn_course_outlines_typ1, :trn_course_outlines_num1, :trn_course_outlines_typ2, :trn_course_outlines_num2, :trn_course_outlines_typ3, :trn_course_outlines_num3, :trn_course_outlines_typ4, :trn_course_outlines_num4, :trn_course_outlines_typ5, :trn_course_outlines_num5, :trn_clinical_asses_tools_typ1, :trn_clinical_asses_tools_num1, :trn_clinical_asses_tools_typ2, :trn_clinical_asses_tools_num2, :trn_clinical_asses_tools_typ3, :trn_clinical_asses_tools_num3, :trn_tutor_perf_tools_utl, :trn_SOPs_typ1, :trn_SOPs_num1, :trn_SOPs_typ2, :trn_SOPs_num2, :trn_SOPs_typ3, :trn_SOPs_num3))
     @form.save
    elsif params.has_key?("form_health_iptt")
     @form = FormHealthIptt.new(params[:form_health_iptt].permit(:start_date, :end_date, :iptt_fp_service_providers, :iptt_active_youth, :iptt_youth_partcipation, :iptt_life_skills, :iptt_SRHR_BCC, :iptt_leaders_reached, :iptt_trained_service_providers))
     @form.save
   
elsif params.has_key?("form_health_hiv")
     @form = FormHealthHiv.new(params[:form_health_hiv].permit(:start_date, :end_date, :hiv_rights_holders, :hiv_lobby_meetings, :hiv_women_htc_pmtct, :hiv_budget_allocation, :hiv_rh_receiving_care, :hiv_women_youth_ovc, :hiv_reconstruction, :hiv_people_htc, :hiv_pychosocial, :hiv_cbccs_constructed, :hiv_cbccs_rehabilitated, :hiv_cc_established, :hiv_child_cbccs, :hiv_child_cc, :hiv_caregiver_ecd, :hiv_caregiver_icdp, :hiv_star_circle_established, :hiv_community_star_circle, :hiv_child_eid, :hiv_viral_load, :hiv_resistance, :hiv_adolescent_life_skills))
     @form.save
   
elsif params.has_key?("form_health_reproductive_health_output_two")
     @form = FormHealthReproductiveHealthOutputTwo.new(params[:form_health_reproductive_health_output_two].permit(:start_date, :end_date, :youth_clubs, :active_clubs, :star_cycle_train_m_less_10, :star_cycle_train_m_10_14, :star_cycle_train_m_15_20, :star_cycle_train_m_21_24, :star_cycle_train_f_less_10, :star_cycle_train_f_10_14, 
:star_cycle_train_f_15_20, :star_cycle_train_f_21_24, :star_cycle_groups_formed, :life_skills_train_m_less_10, :life_skills_train_m_10_14, :life_skills_train_m_15_20, 
:life_skills_train_m_15_20, :life_skills_train_m_21_24, :life_skills_train_f_less_10, :life_skills_train_f_10_14, :life_skills_train_f_15_20, :life_skills_train_f_15_20, :life_skills_train_f_21_24, 
:peer_edu_train_m_less_10, :peer_edu_train_m_10_14, :peer_edu_train_m_15_20, :peer_edu_train_m_21_24, :peer_edu_train_f_less_10, :peer_edu_train_f_10_14, 
:peer_edu_train_f_15_20, :peer_edu_train_f_21_24, :youth_centre_rehabilitated, :bicycles, :leadership))
     @form.save
elsif params.has_key?("form_health_reproductive_health_output_three")
     @form = FormHealthReproductiveHealthOutputThree.new(params[:form_health_reproductive_health_output_three].permit(:start_date, :end_date,
:sens_camp_key_mes_1, :sens_camp_key_mes_2, :sens_camp_key_mes_3, :sens_camp_key_mes_4, :sens_camp_key_mes_5, :sens_camp_key_mes_6, 
:sens_camp_key_mes_7, :sens_camp_key_mes_8, :sens_camp_key_mes_9, :sens_camp_channel_1, :sens_camp_channel_2, :sens_camp_channel_3, 
:sens_camp_channel_4, :sens_camp_channel_5, :sens_camp_channel_6, :sens_camp_channel_7, :sens_camp_channel_8, :sens_camp_channel_9, 
:sens_camp_key_mes_fig_1, :sens_camp_key_mes_fig_2, :sens_camp_key_mes_fig_3, :sens_camp_key_mes_fig_4, :sens_camp_key_mes_fig_5, 
:sens_camp_key_mes_fig_6, :sens_camp_key_mes_fig_7, :sens_camp_key_mes_fig_8, :sens_camp_key_mes_fig_9, :ad_camp_key_mes_1, 
:ad_camp_key_mes_2, :ad_camp_key_mes_3, :ad_camp_key_mes_4, :ad_camp_key_mes_5, :ad_camp_key_mes_6, :ad_camp_key_mes_7, 
:ad_camp_key_mes_8, :ad_camp_key_mes_9, :ad_camp_key_mes_10, :ad_camp_key_mes_11, :ad_camp_key_mes_12,  :ad_camp_key_channel_1, 
:ad_camp_key_channel_2, :ad_camp_key_channel_3, :ad_camp_key_channel_4, :ad_camp_key_channel_5, :ad_camp_key_channel_6, :ad_camp_key_channel_7, 
:ad_camp_key_channel_8, :ad_camp_key_channel_9, :ad_camp_key_channel_10, :ad_camp_key_channel_11, :ad_camp_key_channel_12, :ad_camp_key_mes_fig_1, 
:ad_camp_key_mes_fig_2, :ad_camp_key_mes_fig_3, :ad_camp_key_mes_fig_4, :ad_camp_key_mes_fig_5, :ad_camp_key_mes_fig_6, :ad_camp_key_mes_fig_7, 
:ad_camp_key_mes_fig_8, :ad_camp_key_mes_fig_9, :ad_camp_key_mes_fig_10, :ad_camp_key_mes_fig_11, :ad_camp_key_mes_fig_12, :special_event_days, 
:management_of_youth_clubs, :iec_posters, :iec_10, :iec_flyers, :iec_tshirts, :iec_10121022, :jingles, :jingles_aired, :couples, :counselors, :parliament ))
     @form.save

    elsif params.has_key?("form_health_reproductive_health_output_four")
     @form = FormHealthReproductiveHealthOutputFour.new(params[:form_health_reproductive_health_output_four].permit(:start_date, :end_date, :comm_dia_leaders_m, :comm_dia_leaders_f, :comm_dia_chiefs_m, :comm_dia_chiefs_f, :comm_dia_politicians_m, :comm_dia_politicians_f, :srh_leaders_m, :srh_leaders_f, :srh_chiefs_m, :srh_chiefs_f, :srh_politicians_m, :srh_politicians_f, :sgbv_m, :sgbv_f))
     @form.save
    elsif params.has_key?("form_health_giz")
     @form = FormHealthGiz.new(params[:form_health_giz].permit(:start_date, :end_date, :giz_interv_mcci_child_rights, :giz_interv_adol_srhr, :giz_teach_srhr, :giz_sch_auth_srhr, :giz_claim_holders, :giz_legal_ins, :giz_duty_bear_srhr, :giz_comm_diag, :giz_adol_sch_hiv, :giz_comm_chan, :giz_iec_mat, :giz_child_prot_work, :giz_comm_mobl, :giz_adol_youth_clb, :giz_dist_hiv_prenv, :giz_srhr_opn_dys, :giz_sympo_alhiv, :giz_teen_club_alhiv, :giz_nut_asses, :giz_adol_asses
))
     @form.save
     end

     redirect_to '/form_health/index'
  end
  def mnh
  	@facilities = Facility.all
  end
  def training
    @colleges = College.all
  end
  def hiv
  end

end

app/helpers/form_health_helper.rb
module FormHealthHelper
end

app/views/form_health/giz.html.erb
<script type='text/javascript'>

(function()
{
  if( window.localStorage )
  {
    if( !localStorage.getItem( 'firstLoad' ) )
    {
      localStorage[ 'firstLoad' ] = true;
      window.location.reload();
    }  
    else
      localStorage.removeItem( 'firstLoad' );
  }
})();

</script>
		
<script>
			function assignStartDate() {
				document.getElementById("form_health_giz_start_date").value = $("#start_date_picker").val();
			}
			function assignEndDate() {
				document.getElementById("form_health_giz_end_date").value = $("#end_date_picker").val();
			}

		</script>	
		<div class="page-content">
			<div class="row">
				<div class="col-md-2">
				  	<div class="sidebar content-box" style="display: block;">
                  <ul class="nav">
                      <!-- Main menu -->
                      
                      <li><%= link_to 'Home', home_index_path %></li>

                      <li class="dropdown">
                           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                              Data Entry <b class="caret"></b>
                           </a>
                           <!-- Sub menu -->
                           <ul>
                             <li><a href="#">Resource and Finance</a></li>
                             <li><%= link_to 'Gender Justice', form_gender_index_path %></li>
                             <li><%= link_to 'Health', form_health_index_path %></li>
    			   			 <li><a href="#">Monitoring and Evaluation</a></li>
                          </ul>
                      </li>

                      <li class="dropdown">
                           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                              Reports <b class="caret"></b>
                           </a>
                           <!-- Sub menu -->
                           <ul>
                             <li><a href="#">Resource and Finance</a></li>
                             <li><%= link_to 'Gender Justice', report_gender_index_path %></li>
                             <li><%= link_to 'Health', report_health_index_path %></li>
    			   			 <li><a href="#">Monitoring and Evaluation</a></li>
                          </ul>
                      </li>

                      <li class="dropdown">
                           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                              Documents <b class="caret"></b>
                           </a>
                           <!-- Sub menu -->
                           <ul>
                            <li> <%= link_to 'View', docs_path %></li>
                             <li><%= link_to 'Upload', docs_new_path %></li>
                          </ul>
                      </li>

<!--
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                              Partners <b class="caret"></b>
                          </a>
                           <ul>
                            <li> <%= link_to 'Facilities', facilities_path %></li>
                             <li><%= link_to 'Institutions', forms_new_path %></li>
                          </ul>
                      </li>
            --> 
                  </ul>
               </div>
				</div>
				<div class="col-md-10">
					<div class="row">

					</div>

					<div class="row">
						<div class="col-md-12 panel-warning">
							<div class="content-box-header panel-heading">
								<div class="panel-title ">Data Entry - GIZ</div>
								
								<div class="panel-options">
									<a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
									<a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
								</div>
							</div>
							<div class="content-box-large box-with-header">
								



								<!--form-->
								
								<div class="content-box-large">
									
									<div class="panel-body">





										<%= form_for :form_health_giz, :url => { :action => :create }	 do |f| %>
										

										<!--form action="/forms/create" method="post"-->
										<fieldset>







											<div class="panel-body">





												<%= f.hidden_field :start_date, :value => "1900-01-01"%>
												<%= f.hidden_field :end_date, :value => "2013-12-31" %>

												<table class="table table-bordered">
													<thead>
														<tr>
															<th>Indicator</th>
															<th>Value</th>
														</tr>
													</thead>
													<tbody>
														<tr>
															<td>Start Date</td>
															<td><div class="bfh-datepicker" data-format="y-m-d" data-date="today" id="start_date_picker" onchange="assignStartDate()"></div></td>
														</tr>
														<tr>
															<td>End Date</td>
															<td><div class="bfh-datepicker" data-format="y-m-d" data-date="today" id="end_date_picker" onchange="assignEndDate()"></div></td>
														</tr>
														

														<tr>
															<td colspan = "2">&nbsp;</td>
														</tr>
														<tr>
															<td># of interventions done by MCCI in promoting child rights in the private sector.</td>
															<td><%= f.text_field :giz_interv_mcci_child_rights, autofocus: true, class: "form-control" %></td>
														</tr>
														<tr>
															<td># of interventions identified for investments in adolescent SRHR</td>
															<td><%= f.text_field :giz_interv_adol_srhr, autofocus: true, class: "form-control" %></td>
														</tr>
														<tr>
															<td># of teachers sensitized and are scaling up School SRHR interventions.</td>
															<td><%= f.text_field :giz_teach_srhr, autofocus: true, class: "form-control" %></td>
														</tr>
														<tr>
															<td># of school authorities who have been mobilized in SRHR, GBV and HIV issues.</td>
															<td><%= f.text_field :giz_sch_auth_srhr, autofocus: true, class: "form-control" %></td>
														</tr>
														<tr>
															<td># of claimholders who have knowledge of 3 key Child protection messages</td>
															<td><%= f.text_field :giz_claim_holders, autofocus: true, class: "form-control" %></td>
														</tr>
														<tr>
															<td># of policy and legal instruments strengthen child protection</td>
															<td><%= f.text_field :giz_legal_ins, autofocus: true, class: "form-control" %></td>
														</tr>
														<tr>
															<td>Number and category of duty bearers with knowlege of Child Protection and SRHR</td>
															<td><%= f.text_field :giz_duty_bear_srhr, autofocus: true, class: "form-control" %></td>
														</tr>
														<tr>
															<td># of community diologues conducted</td>
															<td><%= f.text_field :giz_comm_diag, autofocus: true, class: "form-control" %></td>
														</tr>
														<tr>
															<td>number of  adolescents in school youth clubs aware  of adolescent HIV, and SRHR and Child Protection</td>
															<td><%= f.text_field :giz_adol_sch_hiv, autofocus: true, class: "form-control" %></td>
														</tr>
														<tr>
															<td># of mass communication channels disseminating infortmation about adolescents SRHR                                      </td>
															<td><%= f.text_field :giz_comm_chan, autofocus: true, class: "form-control" %></td>
														</tr>
														<tr>
															<td>Number of IEC materials developed</td>
															<td><%= f.text_field :giz_iec_mat, autofocus: true, class: "form-control" %></td>
														</tr>
														<tr>
															<td># of child protection workers trained and are conducting trainings in Jols and case management.</td>
															<td><%= f.text_field :giz_child_prot_work, autofocus: true, class: "form-control" %></td>
														</tr>
														<tr>
															<td>Communities mobilised and are aware of child protection policies</td>
															<td><%= f.text_field :giz_comm_mobl, autofocus: true, class: "form-control" %></td>
														</tr>
														<tr>
															<td># of Adolscents enrolled in youth clubs and are aware of their rights through Jol and children corners</td>
															<td><%= f.text_field :giz_adol_youth_clb, autofocus: true, class: "form-control" %></td>
														</tr>
														<tr>
															<td>number of districts  in which implementing stakeholders have a functional targeted HIV prevention treatment service delivery model for adolescents with HIV, most at risk and vulnerable and are woriking as a unit</td>
															<td><%= f.text_field :giz_dist_hiv_prenv, autofocus: true, class: "form-control" %></td>
														</tr>
														<tr>
															<td># of SRHR open days conducted in six districts</td>
															<td><%= f.text_field :giz_srhr_opn_dys, autofocus: true, class: "form-control" %></td>
														</tr>
														<tr>
															<td>symposium on care ALHIV conducted.</td>
															<td><%= f.text_field :giz_sympo_alhiv, autofocus: true, class: "form-control" %></td>
														</tr>
														<tr>
															<td># of teen Clubs for ALHIV established and functional</td>
															<td><%= f.text_field :giz_teen_club_alhiv, autofocus: true, class: "form-control" %></td>
														</tr>
														<tr>
															<td># of nutritional assesments for adolescents conducted by community nurses </td>
															<td><%= f.text_field :giz_nut_asses, autofocus: true, class: "form-control" %></td>
														</tr>
														<tr>
															<td># of adolescents assesssed nutrtionally by community nurses.</td>
															<td><%= f.text_field :giz_adol_asses, autofocus: true, class: "form-control" %></td>
														</tr>

														
														<tr>
															<td colspan = "2">&nbsp;</td>
														</tr>
														
													</tbody>
												</table>
											</div>




											
										</fieldset>
										<div>
											
											<%= submit_tag "Finish", class:"btn btn-primary" %>
										</div>
										<!--/form-->
										<% end %>

									</div>
								</div>
								




								<br /><br />
							</div>
						</div>
					</div>

				</div>
			</div>
		</div>

		<footer>
			<div class="container">
				
				<div class="copy text-center">
					Copyright 2015 <a href='#'>Compu Networks</a>
				</div>
				
			</div>
		</footer>

app/views/form_health/index.html.erb
  	
    <div class="page-content">
    	<div class="row">
		  <div class="col-md-2">
		    <div class="sidebar content-box" style="display: block;">
                  <ul class="nav">
                      <!-- Main menu -->
                      
                      <li><%= link_to 'Home', home_index_path %></li>

                      <li class="dropdown">
                           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                              Data Entry <b class="caret"></b>
                           </a>
                           <!-- Sub menu -->
                           <ul>
                             <li><a href="#">Resource and Finance</a></li>
                             <li><%= link_to 'Gender Justice', form_gender_index_path %></li>
                             <li><%= link_to 'Health', form_health_index_path %></li>
                   <li><a href="#">Monitoring and Evaluation</a></li>
                          </ul>
                      </li>

                      <li class="dropdown">
                           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                              Reports <b class="caret"></b>
                           </a>
                           <!-- Sub menu -->
                           <ul>
                             <li><a href="#">Resource and Finance</a></li>
                             <li><%= link_to 'Gender Justice', report_gender_index_path %></li>
                             <li><%= link_to 'Health', report_health_index_path %></li>
                   <li><a href="#">Monitoring and Evaluation</a></li>
                          </ul>
                      </li>

                      <li class="dropdown">
                           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                              Documents <b class="caret"></b>
                           </a>
                           <!-- Sub menu -->
                           <ul>
                            <li> <%= link_to 'View', docs_path %></li>
                             <li><%= link_to 'Upload', docs_new_path %></li>
                          </ul>
                      </li>

<!--
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                              Partners <b class="caret"></b>
                          </a>
                           <ul>
                            <li> <%= link_to 'Facilities', facilities_path %></li>
                             <li><%= link_to 'Institutions', forms_new_path %></li>
                          </ul>
                      </li>
            --> 
                  </ul>
               </div>
		  </div>
		  <div class="col-md-10">
		  	<div class="row">

		  	</div>

		  	<div class="row">
		  		<div class="col-md-12 panel-warning">
		  			<div class="content-box-header panel-heading">
	  					<div class="panel-title ">Health - Form selection</div>
						
						<div class="panel-options">
							<a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
							<a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
						</div>
		  			</div>
		  			<div class="content-box-large box-with-header">
This is a Web Based Database Management System for the Norwegian Church Aid. It contains quarterly data and generates reports as required by the NCA's programs. Below are the areas for which this database system stores, analyses and generates reports.



						<br /><br />
						<br /><br />
<ul>
<li><%=link_to 'MNH Activities', form_health_mnh_path%></li>
<li><%=link_to 'Improved Health Training', form_health_training_path%></li>
<li>Reproductive Health</li>
<ul>
<li><%=link_to 'Output 2', form_health_reproductive_health_output_two_path%></li>
<li><%=link_to 'Output 3', form_health_reproductive_health_output_three_path%></li>
<li><%=link_to 'Output 4', form_health_reproductive_health_output_four_path%></li>
</ul>
<li><%=link_to 'HIV Aids', form_health_hiv_path%></li>
<li><%=link_to 'GIZ Program', form_health_giz_path%></li>
</ul>
						<br /><br />
					</div>
		  		</div>
		  	</div>

		  	<div class="content-box-large">
		  	</div>
		  </div>
		</div>
    </div>

    <footer>
         <div class="container">
         
            <div class="copy text-center">
               Copyright 2015 <a href='#'>Compu Networks</a>
            </div>
            
         </div>
      </footer>